language: python

python:
  - 3.5

before_install:
  - pip install codecov

install:
  - pip install -r test_requirements.txt

script:
  - nosetests --with-coverage --cover-package=sam --cover-inclusive

after_success:
  - codecov